indent_style = "Block"
use_small_heuristics = "Max"
where_single_line = true
format_strings = true
merge_imports = true
max_width = 100
normalize_comments = true
use_try_shorthand = true
overflow_delimited_expr = true
fn_single_line = true
